name = "Your Apartment"
image = "assets/locations/apartment_night.jpg"

description = """
Your private sanctuary. Soft lighting, large bed, toys in the drawer.
{{if player.libido >= 80}}You're so horny you can barely think.{{/if}}
"""

exits.downstairs = "downtown_bar"

npcs = [{ name = "mia", schedule = "20:00-23:59 if romanced" }]